
# Excel Template to backend naming mapping

excelname_mapping = {
        'Affected IT-System*': 'customfield_11624',
        'Business Transaktion*': 'customfield_12105',
        'Category': 'customfield_11230',
        'Department': 'customfield_12405',
        'Sub Department': 'customfield_13312',
        'Summary* DAML': 'summary',
        'Issue Type* DAML':'issuetype',
        'Type*': 'customfield_11623',
        'Project*': 'customfield_10419',
        'Market': 'customfield_12107',
        'Brand': 'customfield_12106',
        'Description* DAML': 'description',
        'Assignee* DAML': 'assignee',
        'Reporter* DAML': 'reporter',
        'Component* DAML': 'components',
        'Priority DAML': 'priority',
        'Summary* DC': 'summary',
        'Description* DC': 'description',
        'Issue Type* DAML':'issuetype',
        'Assignee* DC': 'assignee',
        'Reporter* DC': 'reporter',
        'Component* DC': 'components',
        'Contact person (business department)': 'customfield_12406',
        'Contact person (IT)': 'customfield_12407',
        'Priority DC': 'priority',
        'Due-Date implemented': 'customfield_13712',
        'Detailed Type*': 'customfield_13001',
        'Heat-Map': 'customfield_13003',
        'Areas of activity Heatmap': 'customfield_13829',
        'Technical implementation needed*':'customfield_13828',
        'Labels': 'labels',
        }

dc_cols = [
        'Affected IT-System*', 
        'Business Transaktion*', 
        'Department', 
        'Sub Department', 
        'Type*', 
        'Project*', 
        'Brand', 
        'Summary* DC',
        'Description* DC', 
        'Assignee* DC', 
        'Reporter* DC', 
        'Component* DC',
        'Contact person (business department)', 
        'Contact person (IT)',
        'Priority DC', 
        'Due-Date implemented',
        'Detailed Type*',
        'Heat-Map',
        'Areas of activity Heatmap',
        'Technical implementation needed*',
        'Labels',
        ]

daml_cols = [
        'Affected IT-System*', 
        'Business Transaktion*', 
        'Category',
        'Department', 
        'Sub Department', 
        'Summary* DAML', 
        'Type*', 
        'Project*',
        'Market', 
        'Brand', 
        'Description* DAML', 
        'Assignee* DAML', 
        'Reporter* DAML', 
        'Component* DAML', 
        'Priority DAML',
        ]

dtype = {'Due-Date Implemented': 'datetime64[ns]'}

heatmap = {
        'T:Abschaltung': 1,
        'P:Einwilligung': 1,
        'P:Datenschutzerklärung': 1,
        'P:Nutzungsbedingungen': 1,
        'T:Beauskunftung': 1,
        'T:Löschkonzept': 2,
        'P:Löschkonzept': 2,
        'P:Drittlandsübermittlung': 2,
        'T:Verarbeitung_pbD_(HM_P+R)': 3,
        'P:Interessensabwägung': 3,
        'V:ADV': 4,
        'V:Joint-Controllership': 4,
        'T:ITS-Risk': 6,
        'T:Loggingkonzept': 6,
        'T:Rollen-Rechtekonzept': 6,
        'T:Testdaten': 6,
        'T:DatenfelderInaktivierung': 6,
        'T:Mandantenfähigkeit': 6,
        'T:Verschlüsselung': 6,
        'P:Privacybydesign&default': 7,
        'P:Freitextfeld': 6,
        }

heatmap_area = {
        'T:Abschaltung': 'Einwilligungserklärungen',
        'P:Einwilligung': 'Einwilligungserklärungen',
        'P:Datenschutzerklärung': 'Information bei Direkterhebung',
        'P:Nutzungsbedingungen': 'Information bei Direkterhebung',
        'T:Beauskunftung': 'Auskunft',
        'T:Löschkonzept': 'Löschung',
        'P:Löschkonzept': 'Löschung',
        'P:Drittlandsübermittlung': 'Drittlandsübermittlungen',
        'T:Verarbeitung_pbD_(HM_P+R)': 'P/R',
        'P:Interessensabwägung': 'P/R',
        'V:ADV': 'Auftragsverarbeitung',
        'V:Joint-Controllership': 'Gemeinsam Verantwortliche',
        'T:ITS-Risk': 'TOMs',
        'T:Loggingkonzept': 'Loggingkonzept',
        'T:Rollen-Rechtekonzept': 'Rollen-Rechtekonzept',
        'T:Testdaten': 'Testdaten',
        'T:DatenfelderInaktivierung': 'Datenfelder Inaktivierung',
        'T:Mandantenfähigkeit': 'Mandantenfähigkeit',
        'T:Verschlüsselung': 'Verschlüsselung',
        'P:Privacybydesign&default': 'Privacy by design & privacy by default',
        'P:Freitextfeld': '',
        }

template_cols = [
        'Affected IT-System*',
        'Business Transaktion*',
        'Category',
        'Department',
        'Sub Department',
        'Summary* DAML',
        'Type*',
        'Project*',
        'Market',
        'Brand',
        'Description* DAML',
        'Assignee* DAML',
        'Reporter* DAML',
        'Component* DAML',
        'Priority DAML',
        'Comment DAML',
        'Status DAML',
        'Summary* DC',
        'Description* DC',
        'Assignee* DC',
        'Reporter* DC',
        'Component* DC',
        'Contact person (business department)',
        'Contact person (IT)',
        'Priority DC',
        'Due-Date implemented',
        'Comment',
        'Detailed Type*',
        'Technical implementation needed*',
        'Labels',
        'Linked Issue',
        'Status',
        'DAML_Error_message',
        'DC_Error_message',
        ]
